### ISSUE TITLE
Assets not pulled yet. Waiting for 10 seconds... forever

### ISSUE THREAD

**Issue by jakethesnake420** [metadriverse/metadrive#621]
Was working yesterday
 if I install with pip install metadrive-simulator and run:
`python -m metadrive.examples.profile_metadrive`

i get:

```
Start to profile the efficiency of MetaDrive with 1000 maps and ~4 vehicles!
[INFO] Environment: MetaDriveEnv
[INFO] MetaDrive version: 0.4.2.2
[INFO] Sensors: [lidar: Lidar(), side_detector: SideDetector(), lane_line_detector: LaneLineDetector()]
[INFO] Render Mode: none
[INFO] Horizon (Max steps per agent): None
[INFO] Another instance of this program is already running. Wait for the asset pulling finished from another program...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
```
this repeats forever. I know its not my machine because github action tests that worked yesterday are failing today.

if i install master from git and run it i get:

```
/home/user/.pyenv/versions/3.11.4/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Start to profile the efficiency of MetaDrive with 1000 maps and ~4 vehicles!
[INFO] Environment: MetaDriveEnv
[INFO] MetaDrive version: 0.4.2.2
[INFO] Sensors: [lidar: Lidar(), side_detector: SideDetector(), lane_line_detector: LaneLineDetector()]
[INFO] Render Mode: none
[INFO] Horizon (Max steps per agent): None
[WARNING] Assets folder doesn't exist. Begin to download assets... (base_engine.py:753)
[INFO] Pull assets from https://github.com/metadriverse/metadrive/releases/download/MetaDrive-0.4.2.2/assets.zip to /home/user/Projects/metadrive/metadrive/assets.zip
Traceback (most recent call last):                                                                                                                         |
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/Projects/metadrive/metadrive/examples/profile_metadrive.py", line 17, in <module>
    obs, _ = env.reset()
             ^^^^^^^^^^^
  File "/home/user/Projects/metadrive/metadrive/envs/base_env.py", line 519, in reset
    self.lazy_init()  # it only works the first time when reset() is called to avoid the error when render
    ^^^^^^^^^^^^^^^^
  File "/home/user/Projects/metadrive/metadrive/envs/base_env.py", line 406, in lazy_init
    initialize_engine(self.config)
  File "/home/user/Projects/metadrive/metadrive/engine/engine_utils.py", line 12, in initialize_engine
    cls.singleton = cls(env_global_config)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Projects/metadrive/metadrive/engine/base_engine.py", line 54, in __init__
    self.try_pull_asset()
  File "/home/user/Projects/metadrive/metadrive/engine/base_engine.py", line 754, in try_pull_asset
    pull_asset(update=False)
  File "/home/user/Projects/metadrive/metadrive/pull_asset.py", line 82, in pull_asset
    urllib.request.urlretrieve(ASSET_URL, zip_path, *extra_arg)
  File "/home/user/.pyenv/versions/3.11.4/lib/python3.11/urllib/request.py", line 270, in urlretrieve
    block = fp.read(bs)
            ^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.4/lib/python3.11/http/client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.4/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.4/lib/python3.11/ssl.py", line 1269, in recv_into
    self._checkClosed()
  File "/home/user/.pyenv/versions/3.11.4/lib/python3.11/ssl.py", line 1116, in _checkClosed
    raise Exception("Lost Connection")
Exception: Lost Connection
```

**Comment by QuanyiLi** [comment]
@pengzhenghao Could it be raised due to the new lock system?

**Comment by jakethesnake420** [comment]
import unittest
import filelock
import os
import time
import urllib.request
import zipfile
from unittest.mock import patch
import requests
from requests.exceptions import RequestException
import traceback


VERSION = "0.4.2.2"
class TestFileLockWithRealDownload(unittest.TestCase):
    def setUp(self):
        self.zip_lock = 'test.lock'
        self.zip_path = 'test.zip'
        self.ASSET_URL = "https://github.com/metadriverse/metadrive/releases/download/MetaDrive-{}/assets.zip".format(VERSION)  # Replace with your version
        self.TARGET_DIR = 'test_extraction_dir'

        # Create target directory if it doesn't exist
        if not os.path.exists(self.TARGET_DIR):
            os.makedirs(self.TARGET_DIR)

    def tearDown(self):
        # Cleanup downloaded and extracted files
        if os.path.exists(self.zip_path):
            os.remove(self.zip_path)
        if os.path.exists(self.zip_lock):
            os.remove(self.zip_lock)

    def test_file_lock_with_real_download_fails(self):
        lock = filelock.FileLock(self.zip_lock, timeout=1)
        try:
            with lock.acquire():
                print("Pull assets from {} to {}".format(self.ASSET_URL, self.zip_path))
                try:
                    urllib.request.urlretrieve(self.ASSET_URL, self.zip_path)
                except Exception as e:
                    print("Error during file download: {}".format(e))
                    traceback.print_exc()  # This will print the stack trace
                with zipfile.ZipFile(self.zip_path, 'r') as zip_ref:
                    zip_ref.extractall(self.TARGET_DIR)
                print("Successfully downloaded and extracted assets")

        except filelock.Timeout:
            print("Another instance of this program is already running...")
            while os.path.exists(self.zip_lock):
                print("Assets not pulled yet. Waiting for 10 seconds...")
                time.sleep(10)

            print("Assets are now available.")
            
    def test_file_lock_with_real_download_works(self):
        lock = filelock.FileLock(self.zip_lock, timeout=1)
        try:
            with lock.acquire():
                # Simulate logger
                print("Pull assets from {} to {}".format(self.ASSET_URL, self.zip_path))

                # Implementing retry mechanism
                max_retries = 3
                for _ in range(max_retries):
                    try:
                        response = requests.get(self.ASSET_URL, stream=True, timeout=10)
                        with open(self.zip_path, 'wb') as f:
                            for chunk in response.iter_content(chunk_size=8192):
                                f.write(chunk)
                        break
                    except RequestException as e:
                        print(f"Failed to download file: {e}")
                        time.sleep(5)  # wait before retrying
                else:
                    raise Exception("Failed to download file after multiple attempts")

                with zipfile.ZipFile(self.zip_path, 'r') as zip_ref:
                    zip_ref.extractall(self.TARGET_DIR)
                print("Successfully downloaded and extracted assets")

        except filelock.Timeout:
            print("Another instance of this program is already running. Wait for the asset pulling finished from another program...")
            while os.path.exists(self.zip_lock):
                print("Assets not pulled yet. Waiting for 10 seconds...")
                time.sleep(10)

            print("Assets are now available.")


if __name__ == '__main__':
    unittest.main()

**Comment by pengzhenghao** [comment]
Hi did you install metadrive via git clone or pip install metadrive-simulator? It should be fixed by #607 

Thanks for reminding me maybe I should create a new release so the user install via pip install can avoid this issue.

**Comment by pengzhenghao** [comment]
Now I've made a new release #622 

Could you try update MD and see if that works?

**Comment by pengzhenghao** [comment]
![image](https://github.com/metadriverse/metadrive/assets/22206995/9e2ed197-f036-48bd-aca3-b72aa21690d0)

@jakethesnake420 I ran your code it works well with me

**Comment by jakethesnake420** [comment]
> @jakethesnake420 I ran your code it works well with me

Interesting, I get the `Exception: Lost Connection` when i run test_file_lock_with_real_download_fails(). It must be some dependency issue in my openpilot enviroment on github actions and my local PC. I will test your latest fixes.

**Comment by jakethesnake420** [comment]
Tried the latest pip version 0.4.2.3 . 

Just doing `pip install metadrive-simulator` did not fix the issue. I had to do `pip-autoremove metadrive-simulator` and then `pip install metadrive-simulator --no-cache-dir` to make it work.

**Comment by jakethesnake420** [comment]
So actually when I install it in openpilot, i still get the same `Exception: Lost Connection ` even after updating poetry and pip-autoremove metadrive-simulator and then pip install metadrive-simulator --no-cache-dir

**Comment by jakethesnake420** [comment]
I made a script to recursively check all dependency  versions:

```
import subprocess
import json

def get_package_info(package):
    """ Get the version and dependencies of a package. """
    try:
        print(f"Checking {package}...")
        package_info = subprocess.check_output(["pip", "show", package], text=True)
    except subprocess.CalledProcessError:
        # Package not found
        print(f"Package {package} not found.")
        return None, []

    version = None
    dependencies = []

    for line in package_info.splitlines():
        if line.startswith("Version:"):
            version = line.split("Version:")[1].strip()
        elif line.startswith("Requires"):
            deps = line.split("Requires:")[1].strip()
            if deps:
                dependencies = deps.split(", ")

    return version, dependencies

def get_dependency_tree(package, checked_packages=None):
    """ Recursively get the dependency tree of a package."""
    if checked_packages is None:
        checked_packages = {}

    if package in checked_packages:
        # Package already processed
        print(f"{package} has been already processed.")
        return {package: {'version': checked_packages[package], 'dependencies': {}}}

    version, dependencies = get_package_info(package)
    if version is None:
        return {package: "not found"}

    checked_packages[package] = version
    tree = {'version': version, 'dependencies': {}}

    for dep in dependencies:
        sub_deps = get_dependency_tree(dep, checked_packages)
        if sub_deps:
            tree['dependencies'][dep] = sub_deps

    return tree

dependency_tree = get_dependency_tree("metadrive-simulator")
print(json.dumps(dependency_tree, indent=4))

```

Here is the full dependency tree for my installation so you can compare:

```
{
    "version": "0.4.2.3",
    "dependencies": {
        "filelock": {
            "version": "3.13.1",
            "dependencies": {}
        },
        "geopandas": {
            "version": "0.14.2",
            "dependencies": {
                "fiona": {
                    "version": "1.9.5",
                    "dependencies": {
                        "attrs": {
                            "version": "23.2.0",
                            "dependencies": {}
                        },
                        "certifi": {
                            "version": "2023.11.17",
                            "dependencies": {}
                        },
                        "click": {
                            "version": "8.1.7",
                            "dependencies": {}
                        },
                        "click-plugins": {
                            "version": "1.1.1",
                            "dependencies": {
                                "click": {
                                    "click": {
                                        "version": "8.1.7",
                                        "dependencies": {}
                                    }
                                }
                            }
                        },
                        "cligj": {
                            "version": "0.7.2",
                            "dependencies": {
                                "click": {
                                    "click": {
                                        "version": "8.1.7",
                                        "dependencies": {}
                                    }
                                }
                            }
                        },
                        "setuptools": {
                            "version": "69.0.3",
                            "dependencies": {}
                        },
                        "six": {
                            "version": "1.16.0",
                            "dependencies": {}
                        }
                    }
                },
                "packaging": {
                    "version": "23.2",
                    "dependencies": {}
                },
                "pandas": {
                    "version": "2.2.0",
                    "dependencies": {
                        "numpy": {
                            "version": "1.24.2",
                            "dependencies": {}
                        },
                        "python-dateutil": {
                            "version": "2.8.2",
                            "dependencies": {
                                "six": {
                                    "six": {
                                        "version": "1.16.0",
                                        "dependencies": {}
                                    }
                                }
                            }
                        },
                        "pytz": {
                            "version": "2023.3.post1",
                            "dependencies": {}
                        },
                        "tzdata": {
                            "version": "2023.4",
                            "dependencies": {}
                        }
                    }
                },
                "pyproj": {
                    "version": "3.6.1",
                    "dependencies": {
                        "certifi": {
                            "certifi": {
                                "version": "2023.11.17",
                                "dependencies": {}
                            }
                        }
                    }
                },
                "shapely": {
                    "version": "2.0.2",
                    "dependencies": {
                        "numpy": {
                            "numpy": {
                                "version": "1.24.2",
                                "dependencies": {}
                            }
                        }
                    }
                }
            }
        },
        "gymnasium": {
            "version": "0.28.1",
            "dependencies": {
                "cloudpickle": {
                    "version": "3.0.0",
                    "dependencies": {}
                },
                "farama-notifications": {
                    "version": "0.0.4",
                    "dependencies": {}
                },
                "jax-jumpy": {
                    "version": "1.0.0",
                    "dependencies": {
                        "numpy": {
                            "numpy": {
                                "version": "1.24.2",
                                "dependencies": {}
                            }
                        }
                    }
                },
                "numpy": {
                    "numpy": {
                        "version": "1.24.2",
                        "dependencies": {}
                    }
                },
                "typing-extensions": {
                    "version": "4.9.0",
                    "dependencies": {}
                }
            }
        },
        "lxml": {
            "version": "5.1.0",
            "dependencies": {}
        },
        "matplotlib": {
            "version": "3.8.2",
            "dependencies": {
                "contourpy": {
                    "version": "1.2.0",
                    "dependencies": {
                        "numpy": {
                            "numpy": {
                                "version": "1.24.2",
                                "dependencies": {}
                            }
                        }
                    }
                },
                "cycler": {
                    "version": "0.12.1",
                    "dependencies": {}
                },
                "fonttools": {
                    "version": "4.47.2",
                    "dependencies": {}
                },
                "kiwisolver": {
                    "version": "1.4.5",
                    "dependencies": {}
                },
                "numpy": {
                    "numpy": {
                        "version": "1.24.2",
                        "dependencies": {}
                    }
                },
                "packaging": {
                    "packaging": {
                        "version": "23.2",
                        "dependencies": {}
                    }
                },
                "pillow": {
                    "version": "10.2.0",
                    "dependencies": {}
                },
                "pyparsing": {
                    "version": "3.1.1",
                    "dependencies": {}
                },
                "python-dateutil": {
                    "python-dateutil": {
                        "version": "2.8.2",
                        "dependencies": {}
                    }
                }
            }
        },
        "numpy": {
            "numpy": {
                "version": "1.24.2",
                "dependencies": {}
            }
        },
        "opencv-python": {
            "version": "4.9.0.80",
            "dependencies": {
                "numpy": {
                    "numpy": {
                        "version": "1.24.2",
                        "dependencies": {}
                    }
                }
            }
        },
        "panda3d": {
            "version": "1.10.13",
            "dependencies": {}
        },
        "panda3d-gltf": {
            "version": "0.13",
            "dependencies": {
                "panda3d": {
                    "panda3d": {
                        "version": "1.10.13",
                        "dependencies": {}
                    }
                },
                "panda3d-simplepbr": {
                    "version": "0.11.2",
                    "dependencies": {
                        "panda3d": {
                            "panda3d": {
                                "version": "1.10.13",
                                "dependencies": {}
                            }
                        },
                        "typing-extensions": {
                            "typing-extensions": {
                                "version": "4.9.0",
                                "dependencies": {}
                            }
                        }
                    }
                }
            }
        },
        "pandas": {
            "pandas": {
                "version": "2.2.0",
                "dependencies": {}
            }
        },
        "pillow": {
            "pillow": {
                "version": "10.2.0",
                "dependencies": {}
            }
        },
        "progressbar": {
            "version": "2.5",
            "dependencies": {}
        },
        "psutil": {
            "version": "5.9.8",
            "dependencies": {}
        },
        "pygame": {
            "version": "2.5.2",
            "dependencies": {}
        },
        "Pygments": {
            "version": "2.17.2",
            "dependencies": {}
        },
        "pytest": {
            "version": "7.4.4",
            "dependencies": {
                "iniconfig": {
                    "version": "2.0.0",
                    "dependencies": {}
                },
                "packaging": {
                    "packaging": {
                        "version": "23.2",
                        "dependencies": {}
                    }
                },
                "pluggy": {
                    "version": "1.4.0",
                    "dependencies": {}
                }
            }
        },
        "requests": {
            "version": "2.31.0",
            "dependencies": {
                "certifi": {
                    "certifi": {
                        "version": "2023.11.17",
                        "dependencies": {}
                    }
                },
                "charset-normalizer": {
                    "version": "3.3.2",
                    "dependencies": {}
                },
                "idna": {
                    "version": "3.6",
                    "dependencies": {}
                },
                "urllib3": {
                    "version": "2.1.0",
                    "dependencies": {}
                }
            }
        },
        "scipy": {
            "version": "1.12.0",
            "dependencies": {
                "numpy": {
                    "numpy": {
                        "version": "1.24.2",
                        "dependencies": {}
                    }
                }
            }
        },
        "seaborn": {
            "version": "0.13.2",
            "dependencies": {
                "matplotlib": {
                    "matplotlib": {
                        "version": "3.8.2",
                        "dependencies": {}
                    }
                },
                "numpy": {
                    "numpy": {
                        "version": "1.24.2",
                        "dependencies": {}
                    }
                },
                "pandas": {
                    "pandas": {
                        "version": "2.2.0",
                        "dependencies": {}
                    }
                }
            }
        },
        "shapely": {
            "shapely": {
                "version": "2.0.2",
                "dependencies": {}
            }
        },
        "tqdm": {
            "version": "4.66.1",
            "dependencies": {}
        },
        "yapf": {
            "version": "0.40.2",
            "dependencies": {
                "importlib-metadata": {
                    "version": "7.0.1",
                    "dependencies": {
                        "zipp": {
                            "version": "3.17.0",
                            "dependencies": {}
                        }
                    }
                },
                "platformdirs": {
                    "version": "4.1.0",
                    "dependencies": {}
                },
                "tomli": {
                    "version": "2.0.1",
                    "dependencies": {}
                }
            }
        }
    }
}
```
